AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3

AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 40
PerceivedComplexity:
  Enabled: false
Rails:
  Enabled: true