AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 40
PerceivedComplexity:
  Enabled: false